Feature/modernize
malukenho/docheader pull request #37
Opened 2022-05-14 09:43 UTC by Chris53897

Hi, i did some modernizations.

- drop support of php < 7.4 (EOL)
- fix github actions cs2pr
- drop support of symfony 3 (EOL)
- allow symfony 6
- update phpunit 9
- remove deprected psaml option `totallyTyped="true"`
- composer.json allow plugins (as suggested by composer. Otherwise will not work after 22.05.2022 if i read correct)

WDYT?

2022-06-09 09:14 UTC, Chris53897 commented
@malukenho Hi. Can you have a look at this PR?

2022-06-13 07:21 UTC, malukenho requested changes

2022-06-13 07:21 UTC, malukenho commented on .github/workflows/main.yml
> -        php: ['7.1', '7.2', '7.3', '7.4', '8.0']
May we drop support for PHP 7.4? The [EOL](https://www.php.net/supported-versions.php) is nearby.

2022-06-13 07:22 UTC, malukenho commented
Other than the PHP-supported version looks fine.

2022-06-13 13:59 UTC, Chris53897 commented on .github/workflows/main.yml
> -        php: ['7.1', '7.2', '7.3', '7.4', '8.0']
Yes. I did drop support for 7.4, and add features of php8

2022-06-13 14:25 UTC, merged

2022-06-13 14:26 UTC, malukenho commented
I'll tag a version tonight.

2022-07-11 12:36 UTC, Chris53897 commented
@malukenho Can you please tag it?

2022-07-12 09:12 UTC, malukenho commented
@Chris53897 https://github.com/malukenho/docheader/releases/tag/1.0.0